# Getting&CleaningData : Course Project
## Introduction
This repo contains my course project to "Getting & Cleaning Data" course by JHU-Coursera.
It contains:    
-run_analysis.R : Contains the code that performs the Data-Tidying as described in the course-Project   
-CodeBook.Rmd : Describes the variables and the working of the script  
-ReadMe.Rmd : Gives main informations about the repo and how to use the code book and the script  

***

## Files
#### run_analysis.R
The "run_analysis.R"" script requires downloading and unziping the original raw data, which was generated during a set of experiments that study the data collected by a smartphone of subjects in specific positions and activities.  
The code performs transformations on the raw data and returns a Tidy data as an output in .txt format.
It can be launched using RStudio

#### CodeBook.Rmd
Describes the operations performed by the script and the variables of the obtained data

#### TidyAverage.txt
The 2nd output of the script run_analysis.R as described in the 5th step of the project Course

***

##Before Running the script !
Before running the script contained in this repo (run_analysis.R), consider first the folowing steps:

1.  Download the folder of the original raw Data here: [Download](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

2.  Unzip the file and set your RStudio working directory on the obtained file "./UCI HAR Dataset"

3.  Don't change or rename any file within the obtained folder to avoid errors while executing the script

4.  Required Packages: dplyr, plyr, tidyr    

The code in run_analysis.R can be described as a 4-steps code (the script is splitted by comments):

1. Loading and preparing the required data

2. Extracting only the enteries storing the mean or standard deviation for each measurement

3. Merging training and test data to create a first Tidy Dataset

4. Creating a second tidy data set with the average of each Variable for each Activity and each Subject

***

## Code parts explicitly:
#### 1- Loading and preparing the required data
*10-17:* Loading the required datasets and storing them in variables

#### 2- Extracting only the enteries storing the mean or standard deviation for each measurement
*22:* deleting the numbers in the features vector (irrelevant for the study)
*23-24:* selecting the indexes of the features mentionning a mean or standard deviation in the features vector
*29:* extracting only the columns of the training dataset corresponding the the mean/standard deviation of the measurements
*30:* attributing the corresponding features' names to the columns of the obtained train data

*31-32:* joining the corresponding subjects and activity columns to the obtained train data
*36-39:* same as 29-32 applied to the test dataset

*42-43:* by default the subjects and activity values are stored as factors. Turning them into characters.

#### 3- Merging training and test data to create a first Tidy Dataset

*48:* merging the train and test with **rbind()** in one dataset stored in *total*
*52-53:* cleaning the activity labels and attributing them to activity column of *total*
*54-57:* cleaning the names of the *total* variables 
*58:* storing the obtained Tidy data in the *total0* table

####4- Creating a second tidy data set with the average of each Variable for each Activity and each Subject

*63:* creating a new variable within *total* dataset: Subj_Acty=pairs of (subject, activity) separated with "_". The idea is that grouping along two variables is equivalent to grouping allong the variable that contains all the combinations of the these two variables. 
*64:* grouping the *total* data along the *Subj_Acty* variable using **group_by()**

*65:* calculating the average (mean) of all the columns for each pair (subject,activity) using **summarise_each()**

*72:* separating the two variables (subject & activity) stored in the Subj_Acty to turn it into a tidy data: 180 observation= (30 Subject)*(6 Activity)

*76-77:* arranging the obtained tidy data and creating a .txt file version of it using **write.table()**
